name: Deploy LwL to staging
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install firebase-tools
        run: |
          npm install --global yarn firebase-tools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build web
        run: |
          yarn build_staging
