name: Deploy LwL to staging
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install firebbase-tools
        run: |
          npm install --global firebase-tools
