name: Deploy LwL to staging
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install yarn and firebase-tools
        run: |
          npm install --global yarn firebase-tools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install web dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Install function dependencies
        working-directory: ./functions
        run: |
          yarn install --frozen-lockfile
      - name: Build web
        run: |
          yarn build_staging
      - name: Deploy to Firebase
        run: |
          firebase use staging
          firebase deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
